GuestBookPrework-AdrianPacholarz/Models/ErrorViewModel.cs
using System;

namespace GuestBookPrework_AdrianPacholarz.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

GuestBookPrework-AdrianPacholarz/Models/GuestBookViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GuestBookPrework_AdrianPacholarz.Models
{
    public class GuestBookViewModel
    {
        public List<GuestEntryViewModel> allEntries = new List<GuestEntryViewModel>();
    }

}

GuestBookPrework-AdrianPacholarz/Models/GuestEntryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace GuestBookPrework_AdrianPacholarz.Models
{
    public class GuestEntryViewModel
    {
        public string message { get; set; }
        public string name { get; set; }
        public DateTime date { get; set; }

        public GuestEntryViewModel(string message, string name)
        {
            this.message = message;
            this.name = name;
            this.date = DateTime.Now;
        }

        public GuestEntryViewModel(string message, string name, DateTime date)
        {
            this.message = message;
            this.name = name;
            this.date = date;
        }
    }
}

GuestBookPrework-AdrianPacholarz/Controllers/GuestBookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GuestBookPrework_AdrianPacholarz.Models;
using Microsoft.AspNetCore.Mvc;

namespace GuestBookPrework_AdrianPacholarz.Controllers
{
    public class GuestBookController : Controller
    {
        public static GuestBookViewModel guestBook;

        public IActionResult Index()
        {
            guestBook = GetBookWithEntries();
            return View(guestBook);
        }

        public GuestBookViewModel GetBookWithEntries()
        {
            
            var guestBookwithEntries = new GuestBookViewModel();

            guestBookwithEntries.allEntries.Add(new GuestEntryViewModel("Tu byłem", "Codecooler", new DateTime(2014, 03, 02, 21, 37, 18)));
            guestBookwithEntries.allEntries.Add(new GuestEntryViewModel("Tutaj nie byłem", "Mentor", new DateTime(2018, 01, 23, 13, 15, 37)));

            return guestBookwithEntries;
        }

        [HttpPost]
        public IActionResult Index(string feedback, string name)
        {
            guestBook.allEntries.Add(new GuestEntryViewModel(feedback, name));
            return View(guestBook);
        }
    }
}

GuestBookPrework-AdrianPacholarz/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using GuestBookPrework_AdrianPacholarz.Models;

namespace GuestBookPrework_AdrianPacholarz.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

GuestBookPrework-AdrianPacholarz/Views/GuestBook/Index.cshtml
@model GuestBookViewModel
@{
    ViewData["Title"] = "Guest Book";
}
<h1>@ViewData["Title"]</h1>

@if (Model.allEntries.Count == 0)
{
    <text> No one has written an entry yet. </text>
}

<div class="GuestBookEntries">
    @foreach (var entry in Model.allEntries)
    {
        <ul class="GuestEntry">
            <li>@entry.message</li>
            <li><strong>Name: </strong>@entry.name</li>
            <li><strong>Date: </strong>@entry.date</li>
        </ul>
    }
</div>
<form class="NewEntry" onsubmit="return validateForm()" method="post">
    <p><label>Guest entry:</label></p>
    <p><textarea name="feedback" rows="5" cols="50" placeholder="Tell us something about you!"></textarea></p>
    <span id="feedbackError"></span>
    <p><label>Guest name:</label></p>
    <p><input type="text" name="name" placeholder="Your name" /></p>
    <span id="nameError"></span>
    <p><button name="sendButton" type="submit" disabled>Submit</button></p>
</form>
<script src="~/js/GuestEntryScript.js"></script>

GuestBookPrework-AdrianPacholarz/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

GuestBookPrework-AdrianPacholarz/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GuestBookPrework_AdrianPacholarz</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GuestBookPrework_AdrianPacholarz</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="GuestBook" asp-action="Index">GuestBook</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - GuestBookPrework_AdrianPacholarz - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>